// refer to https://github.com/thirdy/durian/blob/master/durian/terms/reference/basetypes.txt

var baseTypes = {} 

baseTypes['Agate Amulet']='amulets'
baseTypes['Amber Amulet']='amulets'
baseTypes['Citrine Amulet']='amulets'
baseTypes['Coral Amulet']='amulets'
baseTypes['Gold Amulet']='amulets'
baseTypes['Jade Amulet']='amulets'
baseTypes['Jet Amulet']='amulets'
baseTypes['Lapis Amulet']='amulets'
baseTypes['Onyx Amulet']='amulets'
baseTypes['Paua Amulet']='amulets'
baseTypes['Turquoise Amulet']='amulets'

baseTypes['Carved Wand']='wands'
baseTypes['Crystal Wand']='wands'
baseTypes['Demon\'s Horn']='wands'
baseTypes['Driftwood Wand']='wands'
baseTypes['Engraved Wand']='wands'
baseTypes['Faun\'s Horn']='wands'
baseTypes['Goat\'s Horn']='wands'
baseTypes['Heathen Wand']='wands'
baseTypes['Imbued Wand']='wands'
baseTypes['Omen Wand']='wands'
baseTypes['Opal Wand']='wands'
baseTypes['Pagan Wand']='wands'
baseTypes['Profane Wand']='wands'
baseTypes['Prophecy Wand']='wands'
baseTypes['Quartz Wand']='wands'
baseTypes['Sage Wand']='wands'
baseTypes['Serpent Wand']='wands'
baseTypes['Spiraled Wand']='wands'
baseTypes['Tornado Wand']='wands'
